baseURL = 'https://realahnet.github.io'
languageCode = 'en-us'
title = 'Ahnet'
theme = 'PaperMod'

[params.profileMode]
enabled = true
title = "Kumail Hanafi"
subtitle = "I exist ðŸ¥²"
imageUrl = "https://avatars.githubusercontent.com/u/57623523"
imageTitle = "Profile Picture"
imageWidth = 300
imageHeight = 300

  [[params.profileMode.buttons]]
  name = "About Me"
  url = "/about"

  [[params.profileMode.buttons]]
  name = "My Blogs"
  url = "/posts"

[params]
    ShowReadingTime = true
    taglist = true
    ShowCodeCopyButtons = true
    ShowBreadCrumbs = true

[[params.socialIcons]]
name = "GitHub"
url = "https://github.com/realahnet"

[[params.socialIcons]]
name = "LinkedIn"
url = "https://linkedin.com/in/kumail-hanafi"

[[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts/"

[[menu.main]]
    identifier = "tags"
    name       = "Tags"
    url        = "/tags"